version: "3.8"
services:
   code_collab_backend:
      container_name: code_collab_backend
      build:
         context: .
         dockerfile: Dockerfile
         args:
            ASPNETCORE_ENVIRONMENT: Development
      ports:
         - "3003:5009"
      environment:
         ASPNETCORE_ENVIRONMENT: Development
         ASPNETCORE_URLS: http://+:5009
      depends_on:
         - code_collab_database

   code_collab_database:
      container_name: code_collab_database
      image: postgres:16
      ports:
         - "54323:5432"
      environment:
         - POSTGRES_USER=${POSTGRES_USER}
         - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
         - POSTGRES_DB=${POSTGRES_DB}
      volumes:
         - code_collab_data:/var/lib/postgresql/data

volumes:
   code_collab_data:
