version: "3.8"

services:
  code-collab-backend:
    container_name: code-collab-backend
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ASPNETCORE_ENVIRONMENT: Production
    ports:
      - "3003:5009"
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5009
      - ConnectionStrings__DefaultConnection=Host=code-collab-database;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      - JwtSettings__Issuer=${JWT_ISSUER}
      - JwtSettings__Audience=${JWT_AUDIENCE}
      - JwtSettings__SecretKey=${JWT_SECRET}
    depends_on:
      - code-collab-database

  code-collab-database:
    container_name: code-collab-database
    image: postgres:16
    ports:
      - "54323:5432"
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - code-collab-data:/var/lib/postgresql/data

volumes:
  code-collab-data:
