import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.css";

import { getCurrentUser } from "./_api/user/get-current-user";
import { UnauthorizedHeader } from "./_components/headers/unauthorized-header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Code Collab",
  description: "Generated by create next app",
};

const RootLayout = async ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  const isLoggedIn = !!(await getCurrentUser());

  return (
    <html lang="en">
      <body className={inter.className}>
        {isLoggedIn ? <div /> : <UnauthorizedHeader />}
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
