import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.css";

import { AuthorizedHeader } from "./_components/headers/authorized-header";
import { UnauthorizedHeader } from "./_components/headers/unauthorized-header";
import { Toaster } from "./_components/ui/sonner";
import { QueryClientProvider } from "./_utils/providers/query-client-provider";
import { getCurrentUser } from "./(auth)/_api/server/get-current-user";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Code Collab",
  description: "Generated by create next app",
};

const RootLayout = async ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  const currentUser = await getCurrentUser();

  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryClientProvider>
          {currentUser !== null ? (
            <AuthorizedHeader currentUser={currentUser} />
          ) : (
            <UnauthorizedHeader />
          )}
          {children}
          <Toaster position="top-right" richColors duration={3000} />
        </QueryClientProvider>
      </body>
    </html>
  );
};

export default RootLayout;
